version: "3.9"

services:
  database:
    image: postgres
    container_name: database_libz
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=libzdb
      - POSTGRES_PASSWORD=libz
      - POSTGRES_DB=libzdb
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: libz
    ports:
      - 4000:4000
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
